'use client'

import { useEffect, useState } from 'react'
import { Lightbulb, Loader2 } from 'lucide-react'
import BoldText from '@/components/ui/BoldText'

interface Props {
  workspaceId: string
}

export default function GoogleAdsActionPlan({ workspaceId }: Props) {
  const [plan, setPlan] = useState<string[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!workspaceId) return
    fetch(`/api/google-ads/action-plan?workspace_id=${workspaceId}`)
      .then(r => r.json())
      .then(d => setPlan(d.action_plan ?? []))
      .catch(() => setPlan([]))
      .finally(() => setLoading(false))
  }, [workspaceId])

  if (loading) {
    return (
      <div className="rounded-xl border border-yellow-200 bg-yellow-50 p-5">
        <div className="flex items-center gap-2 mb-4">
          <Lightbulb className="h-4 w-4 text-yellow-500" />
          <h2 className="text-sm font-semibold text-gray-900">AI Action Plan</h2>
          <span className="rounded-full bg-yellow-100 px-2.5 py-0.5 text-xs font-medium text-yellow-700">
            Generated by Claude AI
          </span>
        </div>
        <div className="flex items-center gap-2 text-sm text-yellow-700">
          <Loader2 className="h-4 w-4 animate-spin" />
          Analysing your account…
        </div>
      </div>
    )
  }

  if (!plan.length) return null

  return (
    <div className="rounded-xl border border-yellow-200 bg-yellow-50 p-5">
      <div className="mb-4 flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <Lightbulb className="h-4 w-4 text-yellow-500" />
          <h2 className="text-sm font-semibold text-gray-900">AI Action Plan</h2>
        </div>
        <span className="rounded-full bg-yellow-100 px-2.5 py-0.5 text-xs font-medium text-yellow-700">
          Generated by Claude AI
        </span>
      </div>
      <ol className="space-y-2.5">
        {plan.map((step, i) => (
          <li key={i} className="flex items-start gap-3">
            <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-yellow-400 text-xs font-bold text-white">
              {i + 1}
            </span>
            <p className="text-sm text-gray-700"><BoldText text={step} /></p>
          </li>
        ))}
      </ol>
    </div>
  )
}
